### ISSUE TITLE
iostream ReadSecret should honor user interrupts

### ISSUE THREAD

**Issue by codergs** [hashicorp/hcp#68]
The `iostreams` packaged system ReadSecret doesn't honor user interrupts.

**Observed:** 
While working on [PR](https://github.com/hashicorp/hcp/pull/65), it was seen that once the user is prompted to provide plaintext via secret value, ctrl +C doesn't cancel the command. The only way to abort is to try something like ctrl +Z and then kill the process. Obviously, I can hit enter and get around this as well. 

```
$ go env | grep -e GOARCH -e GOHOSTOS -e GOOS -e GOVERSION
GOARCH='amd64'
GOHOSTOS='darwin'
GOOS='darwin'
GOVERSION='go1.22.2'
```
**Reproduce:**
Build the CLI using the mentioned [PR](https://github.com/hashicorp/hcp/pull/65), and issue 

```
$ ./bin/hcp auth login
$ ./bin/hcp profile init --vault-secrets
$ ./bin/hcp vault-secrets secrets create test       
Please enter the plaintext secret: 
```
Now try hitting `ctrl + C`.

**Expected Behavior or equivalent:**
```
$ ./bin/hcp vault-secrets secrets create test       
Please enter the plaintext secret: 
```
Pressing ^Ctrl +C should terminate the run gracefully.

**Comment by dadgar** [comment]
Closed by #83
